// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: ec_plan.proto

package ec_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanShard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ShardSize uint64 `protobuf:"varint,2,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
}

func (x *PlanShard) Reset() {
	*x = PlanShard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ec_plan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanShard) ProtoMessage() {}

func (x *PlanShard) ProtoReflect() protoreflect.Message {
	mi := &file_ec_plan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanShard.ProtoReflect.Descriptor instead.
func (*PlanShard) Descriptor() ([]byte, []int) {
	return file_ec_plan_proto_rawDescGZIP(), []int{0}
}

func (x *PlanShard) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PlanShard) GetShardSize() uint64 {
	if x != nil {
		return x.ShardSize
	}
	return 0
}

type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set        string       `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	DataShards uint64       `protobuf:"varint,2,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	Shards     []*PlanShard `protobuf:"bytes,3,rep,name=shards,proto3" json:"shards,omitempty"`
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ec_plan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_ec_plan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_ec_plan_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *Plan) GetDataShards() uint64 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *Plan) GetShards() []*PlanShard {
	if x != nil {
		return x.Shards
	}
	return nil
}

var File_ec_plan_proto protoreflect.FileDescriptor

var file_ec_plan_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x65, 0x63, 0x5f, 0x70, 0x62, 0x22, 0x3e, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x63, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x65, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x65, 0x63, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ec_plan_proto_rawDescOnce sync.Once
	file_ec_plan_proto_rawDescData = file_ec_plan_proto_rawDesc
)

func file_ec_plan_proto_rawDescGZIP() []byte {
	file_ec_plan_proto_rawDescOnce.Do(func() {
		file_ec_plan_proto_rawDescData = protoimpl.X.CompressGZIP(file_ec_plan_proto_rawDescData)
	})
	return file_ec_plan_proto_rawDescData
}

var file_ec_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ec_plan_proto_goTypes = []interface{}{
	(*PlanShard)(nil), // 0: ec_pb.PlanShard
	(*Plan)(nil),      // 1: ec_pb.Plan
}
var file_ec_plan_proto_depIdxs = []int32{
	0, // 0: ec_pb.Plan.shards:type_name -> ec_pb.PlanShard
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ec_plan_proto_init() }
func file_ec_plan_proto_init() {
	if File_ec_plan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ec_plan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanShard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ec_plan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ec_plan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ec_plan_proto_goTypes,
		DependencyIndexes: file_ec_plan_proto_depIdxs,
		MessageInfos:      file_ec_plan_proto_msgTypes,
	}.Build()
	File_ec_plan_proto = out.File
	file_ec_plan_proto_rawDesc = nil
	file_ec_plan_proto_goTypes = nil
	file_ec_plan_proto_depIdxs = nil
}
