// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: suite.proto

package ec_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullPath string `protobuf:"bytes,1,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	Set      string `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	FileSize uint64 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Fid      string `protobuf:"bytes,4,opt,name=fid,proto3" json:"fid,omitempty"`
}

func (x *Frag) Reset() {
	*x = Frag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frag) ProtoMessage() {}

func (x *Frag) ProtoReflect() protoreflect.Message {
	mi := &file_suite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frag.ProtoReflect.Descriptor instead.
func (*Frag) Descriptor() ([]byte, []int) {
	return file_suite_proto_rawDescGZIP(), []int{0}
}

func (x *Frag) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *Frag) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *Frag) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Frag) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type Shard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host  string  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Frags []*Frag `protobuf:"bytes,2,rep,name=frags,proto3" json:"frags,omitempty"`
	Md5   []byte  `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
}

func (x *Shard) Reset() {
	*x = Shard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_suite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_suite_proto_rawDescGZIP(), []int{1}
}

func (x *Shard) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Shard) GetFrags() []*Frag {
	if x != nil {
		return x.Frags
	}
	return nil
}

func (x *Shard) GetMd5() []byte {
	if x != nil {
		return x.Md5
	}
	return nil
}

type Suite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ECid   string   `protobuf:"bytes,1,opt,name=ECid,proto3" json:"ECid,omitempty"`
	Fid    string   `protobuf:"bytes,2,opt,name=fid,proto3" json:"fid,omitempty"`
	Shards []*Shard `protobuf:"bytes,3,rep,name=shards,proto3" json:"shards,omitempty"`
}

func (x *Suite) Reset() {
	*x = Suite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Suite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suite) ProtoMessage() {}

func (x *Suite) ProtoReflect() protoreflect.Message {
	mi := &file_suite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suite.ProtoReflect.Descriptor instead.
func (*Suite) Descriptor() ([]byte, []int) {
	return file_suite_proto_rawDescGZIP(), []int{2}
}

func (x *Suite) GetECid() string {
	if x != nil {
		return x.ECid
	}
	return ""
}

func (x *Suite) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *Suite) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

var File_suite_proto protoreflect.FileDescriptor

var file_suite_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65,
	0x63, 0x5f, 0x70, 0x62, 0x22, 0x64, 0x0a, 0x04, 0x46, 0x72, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x05, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x46,
	0x72, 0x61, 0x67, 0x52, 0x05, 0x66, 0x72, 0x61, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64,
	0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x22, 0x53, 0x0a, 0x05,
	0x53, 0x75, 0x69, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x45, 0x43, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x45, 0x43, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x65, 0x63, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_suite_proto_rawDescOnce sync.Once
	file_suite_proto_rawDescData = file_suite_proto_rawDesc
)

func file_suite_proto_rawDescGZIP() []byte {
	file_suite_proto_rawDescOnce.Do(func() {
		file_suite_proto_rawDescData = protoimpl.X.CompressGZIP(file_suite_proto_rawDescData)
	})
	return file_suite_proto_rawDescData
}

var file_suite_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_suite_proto_goTypes = []interface{}{
	(*Frag)(nil),  // 0: ec_pb.Frag
	(*Shard)(nil), // 1: ec_pb.Shard
	(*Suite)(nil), // 2: ec_pb.Suite
}
var file_suite_proto_depIdxs = []int32{
	0, // 0: ec_pb.Shard.frags:type_name -> ec_pb.Frag
	1, // 1: ec_pb.Suite.shards:type_name -> ec_pb.Shard
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_suite_proto_init() }
func file_suite_proto_init() {
	if File_suite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_suite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Suite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_suite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suite_proto_goTypes,
		DependencyIndexes: file_suite_proto_depIdxs,
		MessageInfos:      file_suite_proto_msgTypes,
	}.Build()
	File_suite_proto = out.File
	file_suite_proto_rawDesc = nil
	file_suite_proto_goTypes = nil
	file_suite_proto_depIdxs = nil
}
